### ISSUE TITLE
host模式，环境变量ip route设为1，iptables就显示找不到

### ISSUE THREAD

**Issue by edwardostara** [ChisBread/chislash#1]
其他问题都解决了，就这个不知道是什么原因。ip route为0，正常使用
![msedge_pZ7Fatbpfr](https://user-images.githubusercontent.com/44975278/173711685-7996e652-cf81-435b-ae1b-d06014251f7a.png)

**Comment by ChisBread** [comment]
需要提供一下：
docker-compose配置，Linux内核版本，docker版本

需要说明的是iptables涉及到内核调用，部分环境可能无法兼容（也就是不能开启透明代理模式）

**Comment by ChisBread** [comment]
刚刚更新了，新的版本提高了兼容性，可以更新镜像再尝试一下。

**Comment by edwardostara** [comment]
> 需要提供一下： docker-compose配置，Linux内核版本，docker版本
> 
> 需要说明的是iptables涉及到内核调用，部分环境可能无法兼容（也就是不能开启透明代理模式）

好的
1.docker-compose
  chislash:
    image: chisbread/chislash:latest
    container_name: chislash
    # 以下样例中的 "/etc/clash/" 代表容器内目录
    environment:
      - TZ=Asia/Shanghai       # optional
      - REQUIRED_CONFIG=/etc/clash/config.yaml # optional 
      # REQUIRED_CONFIG: 不能被覆盖的设置项, 最高优先级 (e.g. /etc/clash/required.yaml)
      - CLASH_HTTP_PORT=7890   # optional (default:7890)
      - CLASH_SOCKS_PORT=7891  # optional (default:7891)
      - CLASH_TPROXY_PORT=7892 # optional (default:7892)
      - CLASH_MIXED_PORT=7893  # optional (default:7893)
      - DASH_PORT=8080         # optional (default:8080) RESTful API端口(对应WebUI http://IP:8080/ui)
      - DASH_PATH=/etc/clash/dashboard/public # optional (default:"/etc/clash/dashboard/public")
      - IP_ROUTE=1             # optional (default:1) 开启透明代理(本机透明代理/作为旁路网关)
      - UDP_PROXY=1            # optional (default:1) 开启透明代理-UDP转发(需要节点支持)
      - IPV6_PROXY=1           # optional (default:1) 开启IPv6透明代理
      - LOG_LEVEL=info         # optional (default:info) 日志等级
      - SECRET=''
      - ENABLE_SUBCONV=1      # optional (default:1) 开启本地订阅转换服务, 指定SUBSCR_URLS, 且没有外部订阅转换服务时, 需要为1
      - SUBCONV_URL=http://127.0.0.1:25500/sub  # optional (default:"http://127.0.0.1:25500/sub") 订阅转换服务地址
      - SUBSCR_URLS=
      # optional 订阅的节点链接, 多个链接用'|'分隔, 会覆盖原有的config.yaml
      - SUBSCR_EXPR=86400                       # optional (default:86400) 订阅过期时间(秒), 下次启动如果过期, 会重新订阅
      - REMOTE_CONV_RULE="http://0.0.0.0:8091/ACL4SSR/Clash/config/ACL4SSR_Online_Full.ini"  
      # optional (default:⬇️) 订阅转换规则
      # REMOTE_CONV_RULE: 默认使用内部服务提供的链接 "http://127.0.0.1:8091/ACL4SSR/Clash/config/ACL4SSR_Online_Full.ini"
      # 在浏览器打开 http://< 服务器IP >:8091/ACL4SSR/Clash/config/ 即可查看内部服务支持的规则列表
      - EXPORT_DIR_PORT=8091
      - EXPORT_DIR_BIND='0.0.0.0'
      - NO_ENGLISH=true        # optional (default:true) 提醒自己这玩意主要是国人用
    volumes:
      - /volume1/docker/chislash/config:/etc/clash # required config.yaml的存放路径
      - /dev:/dev                   # optional 用于自动挂载TPROXY模块
      - /lib/modules:/lib/modules   # optional 用于自动挂载TPROXY模块
    network_mode: "host"            # required 如果开启IP_ROUTE, 则必须是host
    privileged: true                # required 如果开启IP_ROUTE, 则必须是true
    restart: unless-stopped

2.Linux内核
4.4.180+

3.docker版本
Docker version 20.10.3

**Comment by edwardostara** [comment]
我已经自己编译了，xt_owner.ko、xt_connmark.ko和xt_TPROXY.ko，加载成功，也生效了，但是遇到了规则文件服务未能启动的问题，请问我该怎么解决？

**Comment by ChisBread** [comment]
发现问题了！
EXPORT_DIR_BIND='0.0.0.0'
改成 EXPORT_DIR_BIND=0.0.0.0 试试

**Comment by ChisBread** [comment]
> 发现问题了！ EXPORT_DIR_BIND='0.0.0.0' 改成 EXPORT_DIR_BIND=0.0.0.0 试试

这个被解析成了"'0.0.0.0'" 所以无法识别，是我写文档时疏忽了
